import '../../features/proyectos/dominio/modelos/proyecto_modelo.dart';
import '../../features/proyectos/dominio/modelos/ubicacion_proyecto_modelo.dart';

List<ProyectoModelo> crearProyectosDemo() {
  final hoy = DateTime.now();

  PagoModelo crearPago({
    required String id,
    required String hito,
    required double monto,
    required DateTime fechaPrevista,
    required bool estaPagado,
  }) {
    return PagoModelo(
      id: id,
      hito: hito,
      monto: monto,
      fechaPrevista: fechaPrevista,
      estaPagado: estaPagado,
    );
  }

  ProyectoModelo crearProyecto({
    required String id,
    required String nombre,
    required String codigoProceso,
    required String direccion,
    required String etapa,
    required double presupuesto,
    required double certificado,
    required double comprometido,
    required double devengado,
    required double pagado,
    required DateTime fechaInicio,
    required DateTime fechaFin,
    required String formaPago,
    required List<PagoModelo> pagos,
    UbicacionProyectoModelo? ubicacion,
    double porcentajeAvanceFisico = 0,
    DateTime? fechaActualizacionFisica,
    String codigoPartida = '73.06.06',
    String denominacionPartida = 'Servicios técnicos especializados',
  }) {
    return ProyectoModelo(
      id: id,
      nombre: nombre,
      codigoProceso: codigoProceso,
      direccion: direccion,
      poaMeta: 'Meta operativa del POA 2026',
      pacItem: 'PAC-2026-$id',
      etapa: etapa,
      presupuestoAsignado: presupuesto,
      certificado: certificado,
      comprometido: comprometido,
      devengado: devengado,
      pagado: pagado,
      fechaInicio: fechaInicio,
      fechaFin: fechaFin,
      formaPago: formaPago,
      partidas: [
        PartidaModelo(
          codigo: codigoPartida,
          denominacion: denominacionPartida,
          monto: presupuesto,
        ),
      ],
      pagos: pagos,
      ubicacion: ubicacion,
      porcentajeAvanceFisico: porcentajeAvanceFisico,
      fechaActualizacionFisica: fechaActualizacionFisica,
    );
  }

  return [
    crearProyecto(
      id: 'PROY-001',
      nombre: 'Rehabilitación vial avenida Daniel León Borja',
      codigoProceso: 'MCO-GADMR-2026-014',
      direccion: 'Obras Públicas',
      etapa: 'Ejecución',
      presupuesto: 420000,
      certificado: 420000,
      comprometido: 390000,
      devengado: 260000,
      pagado: 210000,
      fechaInicio: hoy.subtract(const Duration(days: 120)),
      fechaFin: hoy.add(const Duration(days: 150)),
      formaPago: 'Pagos parciales',
      porcentajeAvanceFisico: 0.55,
      fechaActualizacionFisica: hoy.subtract(const Duration(days: 4)),
      ubicacion: const UbicacionProyectoModelo(
        tipoGeometria: TipoGeometriaProyecto.linea,
        referenciaUbicacion: 'Trazado referencial centro de Riobamba',
        coordenadas: [
          CoordenadaModelo(latitud: -1.6685, longitud: -78.6558),
          CoordenadaModelo(latitud: -1.6669, longitud: -78.6545),
          CoordenadaModelo(latitud: -1.6651, longitud: -78.6535),
          CoordenadaModelo(latitud: -1.6638, longitud: -78.6524),
        ],
      ),
      pagos: [
        crearPago(
          id: 'PAG-001',
          hito: 'Anticipo contractual',
          monto: 80000,
          fechaPrevista: hoy.subtract(const Duration(days: 90)),
          estaPagado: true,
        ),
        crearPago(
          id: 'PAG-002',
          hito: 'Avance de obra 40 %',
          monto: 45000,
          fechaPrevista: hoy.subtract(const Duration(days: 38)),
          estaPagado: false,
        ),
      ],
    ),
    crearProyecto(
      id: 'PROY-002',
      nombre: 'Mantenimiento vial en barrios del norte',
      codigoProceso: 'MCO-GADMR-2026-021',
      direccion: 'Obras Públicas',
      etapa: 'Ejecución',
      presupuesto: 180000,
      certificado: 180000,
      comprometido: 180000,
      devengado: 120000,
      pagado: 70000,
      fechaInicio: hoy.subtract(const Duration(days: 95)),
      fechaFin: hoy.add(const Duration(days: 90)),
      formaPago: 'Pagos parciales',
      porcentajeAvanceFisico: 0.68,
      fechaActualizacionFisica: hoy.subtract(const Duration(days: 5)),
      ubicacion: const UbicacionProyectoModelo(
        tipoGeometria: TipoGeometriaProyecto.linea,
        referenciaUbicacion: 'Sector norte referencial',
        coordenadas: [
          CoordenadaModelo(latitud: -1.6514, longitud: -78.6539),
          CoordenadaModelo(latitud: -1.6499, longitud: -78.6522),
          CoordenadaModelo(latitud: -1.6484, longitud: -78.6512),
          CoordenadaModelo(latitud: -1.6469, longitud: -78.6504),
        ],
      ),
      pagos: [
        crearPago(
          id: 'PAG-003',
          hito: 'Primer avance',
          monto: 70000,
          fechaPrevista: hoy.subtract(const Duration(days: 58)),
          estaPagado: true,
        ),
        crearPago(
          id: 'PAG-004',
          hito: 'Segundo avance',
          monto: 35000,
          fechaPrevista: hoy.subtract(const Duration(days: 33)),
          estaPagado: false,
        ),
      ],
    ),
    crearProyecto(
      id: 'PROY-003',
      nombre: 'Estudios para mejoramiento de red vial',
      codigoProceso: 'CDC-GADMR-2026-007',
      direccion: 'Obras Públicas',
      etapa: 'Precontractual',
      presupuesto: 75000,
      certificado: 75000,
      comprometido: 30000,
      devengado: 0,
      pagado: 0,
      fechaInicio: hoy.add(const Duration(days: 15)),
      fechaFin: hoy.add(const Duration(days: 105)),
      formaPago: 'Contra entrega',
      pagos: const [],
    ),
    crearProyecto(
      id: 'PROY-004',
      nombre: 'Reforestación urbana en parques barriales',
      codigoProceso: 'SIE-GADMR-2026-009',
      direccion: 'Ambiente',
      etapa: 'Ejecución',
      presupuesto: 130000,
      certificado: 130000,
      comprometido: 110000,
      devengado: 75000,
      pagado: 45000,
      fechaInicio: hoy.subtract(const Duration(days: 80)),
      fechaFin: hoy.add(const Duration(days: 80)),
      formaPago: 'Pagos parciales',
      porcentajeAvanceFisico: 0.58,
      fechaActualizacionFisica: hoy.subtract(const Duration(days: 3)),
      ubicacion: const UbicacionProyectoModelo(
        tipoGeometria: TipoGeometriaProyecto.area,
        referenciaUbicacion: 'Parque barrial referencial',
        coordenadas: [
          CoordenadaModelo(latitud: -1.6742, longitud: -78.6522),
          CoordenadaModelo(latitud: -1.6732, longitud: -78.6508),
          CoordenadaModelo(latitud: -1.6719, longitud: -78.6518),
          CoordenadaModelo(latitud: -1.6728, longitud: -78.6534),
        ],
      ),
      pagos: [
        crearPago(
          id: 'PAG-005',
          hito: 'Entrega de plantas',
          monto: 45000,
          fechaPrevista: hoy.subtract(const Duration(days: 42)),
          estaPagado: true,
        ),
        crearPago(
          id: 'PAG-006',
          hito: 'Segundo hito de siembra',
          monto: 25000,
          fechaPrevista: hoy.subtract(const Duration(days: 19)),
          estaPagado: false,
        ),
      ],
    ),
    crearProyecto(
      id: 'PROY-005',
      nombre: 'Sistema de riego para parques urbanos',
      codigoProceso: 'LIC-GADMR-2026-003',
      direccion: 'Ambiente',
      etapa: 'Ejecución',
      presupuesto: 165000,
      certificado: 165000,
      comprometido: 130000,
      devengado: 98000,
      pagado: 98000,
      fechaInicio: hoy.subtract(const Duration(days: 110)),
      fechaFin: hoy.add(const Duration(days: 55)),
      formaPago: 'Pagos parciales',
      porcentajeAvanceFisico: 0.59,
      fechaActualizacionFisica: hoy.subtract(const Duration(days: 6)),
      ubicacion: const UbicacionProyectoModelo(
        tipoGeometria: TipoGeometriaProyecto.punto,
        referenciaUbicacion: 'Parque urbano referencial',
        coordenadas: [
          CoordenadaModelo(latitud: -1.6605, longitud: -78.6571),
        ],
      ),
      pagos: [
        crearPago(
          id: 'PAG-007',
          hito: 'Primer avance',
          monto: 48000,
          fechaPrevista: hoy.subtract(const Duration(days: 34)),
          estaPagado: true,
        ),
        crearPago(
          id: 'PAG-008',
          hito: 'Segundo avance',
          monto: 50000,
          fechaPrevista: hoy.subtract(const Duration(days: 5)),
          estaPagado: true,
        ),
      ],
    ),
    crearProyecto(
      id: 'PROY-006',
      nombre: 'Modernización del portal de trámites municipales',
      codigoProceso: 'SIE-GADMR-2026-018',
      direccion: 'Tecnologías de la Información',
      etapa: 'Ejecución',
      presupuesto: 145000,
      certificado: 145000,
      comprometido: 140000,
      devengado: 116000,
      pagado: 116000,
      fechaInicio: hoy.subtract(const Duration(days: 130)),
      fechaFin: hoy.add(const Duration(days: 45)),
      formaPago: 'Pagos parciales',
      porcentajeAvanceFisico: 0.80,
      fechaActualizacionFisica: hoy.subtract(const Duration(days: 2)),
      ubicacion: const UbicacionProyectoModelo(
        tipoGeometria: TipoGeometriaProyecto.punto,
        referenciaUbicacion: 'Dependencia municipal referencial',
        coordenadas: [
          CoordenadaModelo(latitud: -1.6664, longitud: -78.6543),
        ],
      ),
      pagos: [
        crearPago(
          id: 'PAG-009',
          hito: 'Desarrollo inicial',
          monto: 55000,
          fechaPrevista: hoy.subtract(const Duration(days: 78)),
          estaPagado: true,
        ),
        crearPago(
          id: 'PAG-010',
          hito: 'Implementación y pruebas',
          monto: 61000,
          fechaPrevista: hoy.subtract(const Duration(days: 12)),
          estaPagado: true,
        ),
      ],
    ),
    crearProyecto(
      id: 'PROY-007',
      nombre: 'Sistema de seguimiento POA y PAC',
      codigoProceso: 'CDC-GADMR-2026-012',
      direccion: 'Tecnologías de la Información',
      etapa: 'Contractual',
      presupuesto: 80000,
      certificado: 80000,
      comprometido: 60000,
      devengado: 40000,
      pagado: 40000,
      fechaInicio: hoy.subtract(const Duration(days: 40)),
      fechaFin: hoy.add(const Duration(days: 110)),
      formaPago: 'Pagos parciales',
      pagos: [
        crearPago(
          id: 'PAG-011',
          hito: 'Diseño y levantamiento',
          monto: 40000,
          fechaPrevista: hoy.subtract(const Duration(days: 8)),
          estaPagado: true,
        ),
      ],
    ),
    crearProyecto(
      id: 'PROY-008',
      nombre: 'Equipamiento de centros digitales comunitarios',
      codigoProceso: 'SIE-GADMR-2026-020',
      direccion: 'Tecnologías de la Información',
      etapa: 'Cierre',
      presupuesto: 110000,
      certificado: 110000,
      comprometido: 105000,
      devengado: 105000,
      pagado: 105000,
      fechaInicio: hoy.subtract(const Duration(days: 200)),
      fechaFin: hoy.subtract(const Duration(days: 10)),
      formaPago: 'Contra entrega',
      porcentajeAvanceFisico: 0.95,
      fechaActualizacionFisica: hoy.subtract(const Duration(days: 8)),
      ubicacion: const UbicacionProyectoModelo(
        tipoGeometria: TipoGeometriaProyecto.punto,
        referenciaUbicacion: 'Centro digital comunitario referencial',
        coordenadas: [
          CoordenadaModelo(latitud: -1.6768, longitud: -78.6498),
        ],
      ),
      pagos: [
        crearPago(
          id: 'PAG-012',
          hito: 'Pago final',
          monto: 105000,
          fechaPrevista: hoy.subtract(const Duration(days: 15)),
          estaPagado: true,
        ),
      ],
    ),
    crearProyecto(
      id: 'PROY-009',
      nombre: 'Actualización del Plan de Desarrollo Territorial',
      codigoProceso: 'CDC-GADMR-2026-024',
      direccion: 'Planificación',
      etapa: 'Preparatoria',
      presupuesto: 90000,
      certificado: 90000,
      comprometido: 20000,
      devengado: 0,
      pagado: 0,
      fechaInicio: hoy.add(const Duration(days: 20)),
      fechaFin: hoy.add(const Duration(days: 190)),
      formaPago: 'Pagos parciales',
      pagos: const [],
    ),
    crearProyecto(
      id: 'PROY-010',
      nombre: 'Estudios de movilidad urbana sostenible',
      codigoProceso: 'CDC-GADMR-2026-027',
      direccion: 'Planificación',
      etapa: 'Precontractual',
      presupuesto: 120000,
      certificado: 120000,
      comprometido: 80000,
      devengado: 0,
      pagado: 0,
      fechaInicio: hoy.add(const Duration(days: 8)),
      fechaFin: hoy.add(const Duration(days: 135)),
      formaPago: 'Contra entrega',
      pagos: const [],
    ),
  ];
}